### PR TITLE
Try to fix #277 by deleting verbose info

### LINKED ISSUE #277: Too slow response from stackage.org/feed/lts
The atom feed https://www.stackage.org/feed/lts responds too slowly.
For example `wget https://www.stackage.org/feed/lts` takes about 20 seconds from my desktop.
This seems to cause request timeouts always when the RSS integration of Slack with which we subscribe to https://www.stackage.org/feed/lts.

The RSS integration of Slack in our workspace doesn't notify any updates for more than 4 months.
I suspect this problem is fixed by fixing the slowdown.

### PR DESCRIPTION
**Pull request by igrep**
Problem
====

Too slow response from stackage.org/feed/.
So slow that my favorite RSS client (Slack's RSS integration) doesn't work due to timeout.
See https://github.com/fpco/stackage-server/issues/277 for details.

How?
====

Delete the content of the feed.

Why?
====

I can't confirm it's the true cause of the slowdown (because the server is too hard to run on my machine!).
But anyway I think the html content of the feed is too much:
I just want to know the new LTS Haskell is released by the feed.
I'll click the link if I do want to see the detailed updates.

In addition, there's a reason generating the content causes the slowdown:
Other pages using `getSnapshots` (e.g. https://www.stackage.org/snapshots, https://www.stackage.org/)
are not as slow as https://www.stackage.org/feed/.
So the `getSnapshots` query dosen't seem to be the biggest cause.
And the left possible cause is `mkFeed`.

NOTE
====

I've tested nothing because it's too hard to run this app
without configuring my AWS account.

### CODE REVIEW

**Comment by snoyberg** [comment]
I haven't had trouble with the feed myself. And simply removing the behavior isn't something I'd like to do. If you make the change conditional on a query string parameter or similar, I'd be much more open to the idea.

**Comment by igrep** [comment]
Okay, I added `withDiff` as a query parameter: https://github.com/fpco/stackage-server/pull/282/commits/cc7b12dcd78ce8b3080a23d04afa8d8fb11d7708#diff-405ef76168be2a70f7fce41c72e1054eR64

**Comment by snoyberg** [comment]
Thanks!

**Comment by igrep** [comment]
Thank you! Now `curl https://www.stackage.org/feed/lts?withDiff=False` runs fast enough.
The RSS reader hasn't show anything yet, but it'll resume after new LTS Haskell is published!

**Pull request merged**
