### PR TITLE
Add sitemap #20

### PR DESCRIPTION
**Pull request by DanBurton**

### CODE REVIEW

**Comment by chrisdone** [comment]
Commit looks good! Question: as Google expects to find the `sitemap.xml` by being told it in `robots.txt`, how do we make robots.txt aware of this? I see there's already a `RobotsR` root for Yesod just above your sitemap line, but I'm not sure how it's generated, probably something in Foundation can be configured. Can you check it out?

**Comment by chrisdone** [comment]
Or alternatively we can just submit it to the Google sitemap page, I guess?

**Comment by snoyberg** [comment]
See:
https://www.stackage.org/haddock/nightly-2015-03-23/yesod-sitemap-1.4.0.1/src/Yesod-Sitemap.html#robots

**Comment by DanBurton** [comment]
Since there's a disallow entry in robots.txt, it made more sense to me to just put the sitemap in manually. I'm not sure google will restrict itself to crawling only the sitemap. Was this the right choice?

**Comment by snoyberg** [comment]
Yes, definitely the right choice. By linking to that robots code I just meant to provide information on how to specify the sitemap, not indicate that the function itself should be used.

**Comment by chrisdone** [comment]
Ahh, there was already a `robots.txt`. Cool. I'll test this out locally.

**Comment by chrisdone** [comment]
Looks good. Nice work!

**Pull request merged**
