### PR TITLE
Snapshot diff

### PR DESCRIPTION
**Pull request by zudov**
Simple snapshot diffing
screenshot

### CODE REVIEW

**Comment by zudov** [comment]
Closes #120

**Comment by DanBurton** [comment]
:+1: I love this feature.

**Comment by snoyberg** [comment]
Was closing the PR intentional? Are you planning on opening a new one? This
does look great

**Comment by zudov** [comment]
@snoyberg I didn't close PR, and it looks like open to me.

I think we can merge it now if there is no objections.

**Comment by snoyberg** [comment]
Oh, I misread "closes" as "closed". I'll review now

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
