### PR TITLE
Download handler

### PR DESCRIPTION
**Pull request by DanBurton**
@snoyberg PTAL

You can try out the `stackage-setup` executable via the following steps:

Download stackage-setup from your dev server:
* `git checkout download-handler`
* `yesod devel`
* browse to [https://localhost:3443/download](https://localhost:3443/download)
* Click the link for stackage-setup

Set up the config file to use your local dev server. You must override the default, since the default is `https://www.stackage.org`, which doesn't have these changes live yet. (It will get mad at the dev server's fake https creds, so just use http.)
* `mkdir -p ~/.stackage`
* `echo "stackage-host: http://localhost:3000" > ~/.stackage/config`

Run stackage-setup
* Open a terminal and `cd` to your downloads folder
* `chmod +x stackage-setup`
* `./stackage-setup ghc-7.8`

There are still things to unstub, but I believe this branch is in a state that is ready to safely go live.

### CODE REVIEW

**Comment by snoyberg** [comment]
Two comments:

1. I don't want the executable to be in this repo. Storing large files is a bad idea for a Git repo in general.
2. I'd prefer if the YAML config file went into https://github.com/fpco/stackage-content so it can be easily updated without a code redeploy.

**Comment by rvion** [comment]
in case it is usefull:
https://github.com/blog/1986-announcing-git-large-file-storage-lfs (April 8, 2015)

**Comment by snoyberg** [comment]
Thanks for the pointer. In this case, we need to provide for HTTPS download of these files for end users. Do you know if LFS supports that? I can't tell from that blog post.

**Comment by rvion** [comment]
yes they seems to provide https. 
From https://github.com/github/git-lfs: 

    [...]
    Large files are synced separately to a configurable Git LFS server over HTTPS, so you are not 
    limited in where you push your Git repository.
    [...]

This being said, the service is relatively new, and still in Beta (signup for early access opened a few fays ago).
Not sure it worth jumping to it when S3 does the job.

**Comment by snoyberg** [comment]
Good point, worth considering for the future though.

**Comment by rvion** [comment]
some more notes to consider:
- (positive) Clients and servers can make use of all the features of HTTPS, such as caching content locally on a CDN, resumable uploads and downloads, or performing requests in parallel for faster transfers.
- (positive) Large files are synced separately to a configurable Git LFS server over HTTPS, so you are not limited in where you push your Git repository.
- (negative) mostly only one opensource implementation for now beside github: https://github.com/github/lfs-test-server

**Comment by DanBurton** [comment]
I've rehosted the executable to s3 and the yaml to stackage-content.

**Comment by snoyberg** [comment]
:+1:

**Pull request merged**
