### PR TITLE
Update for lts-3

### PR DESCRIPTION
**Pull request by zudov**
It is WIP, but it already compiles and seem to work fine.

I open a PR for discussion and questions.

### CODE REVIEW

**Comment by zudov** [comment]
First question: Do you think we need to keep it compatible with ghc-7.8.

For now, I don't see any strong reason to do so.

**Comment by DanBurton** [comment]
:+1: I don't see any reason to keep compatible with ghc 7.8.

I have a couple of not-very-important thoughts:
* cabal file: some deps that used to have upper bounds should probably now have heightened lower bounds.
* stack.yaml: I'd like to see it use LTS-3.8 rather than 3.2.

**Comment by zudov** [comment]
@DanBurton Yes, of course. I planned to set cabal lower bounds as in the snapshot + the higher bound according to PVP. And well, I've put 3.2 there just because much of it was built on my machine.

**Comment by snoyberg** [comment]
I agree about dropping 7.8 support; we're building an app, not a library, so having a specific configuration that works is fine. Given that: I'm also not too concerned about version ranges in the .cabal file: as long as Stack can build it with its specified stack.yaml, I'm OK with it.

I've just pushed a commit to the repo to update the Travis configuration to use Stack instead of cabal-install. Once that's passing, you'll probably want to rebase to avoid getting the current spurious dependency solver fails from Travis.

Thanks for this. I think I was unable to do this previously due to some issues with the Haddock library, but apparently those no longer exist.

**Comment by zudov** [comment]
@snoyberg Great.

Interestingly [that is the only change](https://github.com/fpco/stackage-server/pull/124/files#diff-86e80d3ccd238703c38841c86bf8ec11L13) which I had to make due to the updates in the `haddock-library`.

**Comment by snoyberg** [comment]
I just introduced a merge conflict. I'll resolve it and push to a ghc-7.10 branch for Travis to test.

**Comment by zudov** [comment]
The cabal file [diff](https://github.com/fpco/stackage-server/pull/124/files#diff-600a2b86a30b3da51814e46089e20521L87) gives an overview of the dependencies' updates. It would be great if someone who is familiar with codebase and library ecosystem could take a close look and collect some observations on how we can use this hot news stuff.

For example: #126, #125

**Comment by zudov** [comment]
@snoyberg OK, looks like it's ready for review and merge now.

**Comment by snoyberg** [comment]
Merged, thanks!

**Comment by zudov** [comment]
\o/

**Pull request merged**
